### ISSUE TITLE
Installing the plugin breaks a test on OS X El Capitan

### ISSUE THREAD

**Issue by DavidCsordas** [mahmoudimus/nose-timer#73] opened 2016-06-15 09:03 UTC
Installing the plugin breaks a test with TimeoutError (regardless of running them with or without benchmarking). After uninstall, the test works just fine.

Setup: Python 2.7, OS X El Capitan (it works with the same Python version on a Yosemite setup)

Test case structure: The test starts up a flask server as a subprocess, then issues an HTTP request against it. This is the request which times out.

**Comment by skudriashev** [comment] 2016-06-15 09:51
@DavidCsordas, could you please give more details: test that fails, command and run output. This will help to understand the issue. Thanks.

**Comment by DavidCsordas** [comment] 2016-06-15 10:13
I've added some information about how the test works, I don't think I have the liberty to copy our code here. I'm happy to help if you have more specific questions.

Timeout is thrown by our code, the HTTP GET response times out.

Issue can be reproduced even if the timer plugin is not run, so command is --with-timer or just running without it (probably irrelevant).

**Comment by skudriashev** [comment] 2016-06-15 10:15
@DavidCsordas, if issue is reproduced even if plugin is not enabled then the issue is not related to plugin at all.

**Comment by DavidCsordas** [comment] 2016-06-15 10:20
@skudriashev Isn't plugin loaded even if not run? My guess is that it can be platform related somehow.

**Comment by skudriashev** [comment] 2016-06-15 10:22
@DavidCsordas, so if you remove the plugin - there is no error?

**Comment by DavidCsordas** [comment] 2016-06-15 10:24
@skudriashev Exactly.

**Comment by skudriashev** [comment] 2016-06-15 10:25
@DavidCsordas, can you provide a stacktrace of that error?

**Comment by DavidCsordas** [comment] 2016-06-15 10:30
@skudriashev Here you are:

`Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/thorn/dev/sse/src/test/helper/tests.py", line 166, in test_run_and_get
    response = get()
  File "/Users/thorn/dev/sse/lib/Timeout.py", line 36, in _2
    raise TimeoutError('took too long')
TimeoutError: took too long`

**Comment by skudriashev** [comment] 2016-06-15 10:59
@DavidCsordas, doesn't really help...

**Comment by skudriashev** [comment] 2016-06-15 11:03
@DavidCsordas, do you have production env. based on Mac? It works perfectly on linux :smirk:

**Comment by DavidCsordas** [comment] 2016-06-15 11:06
@skudriashev Yeah, guessed it won't help (doesn't help us either). And it works perfectly on Yosemite, too.

**Comment by skudriashev** [comment] 2016-06-15 11:11
@DavidCsordas, let's close this issue until we have more details that will help to fix the issue.

**Closed by skudriashev** 2016-06-15 11:11 UTC

**Comment by DavidCsordas** [comment] 2016-06-15 11:14
@skudriashev Well, I guess... Will check back if we have a lead.

**Comment by skudriashev** [comment] 2016-06-15 11:15
@DavidCsordas, sure. Thanks!

**Comment by DavidCsordas** [comment] 2016-06-16 08:58
@skudriashev fyi, hacking out the platform branch actually made the plugin work (and stop crashing tests) on El Captain:

`
# Windows and Python 2.7 multiprocessing don't marry well.
_results_queue = None

#if not IS_NT:
if 0:  # <-- this line here
`

**Comment by skudriashev** [comment] 2016-06-16 09:54
@DavidCsordas, what is stored here `os.name` on your OS?

**Comment by DavidCsordas** [comment] 2016-06-16 12:06
@skudriashev 'posix', as expected.
